- docs/Base/AbordagemNaoEspecifica/design_sprint.md
- docs/README.md
Criação do documento de design sprint
> Design sprint

- docs/Base/AbordagemNaoEspecifica/mapa_mental.md
> Documento de mapa mental

- docs/Base/IniciativasExtras/iniciativas_extras.md
- [ xAny dependent changes have been merged and published in downstream modules.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …
> docs: criacao doc iniciativa extra

- docs/AtasDeReunião/Ata_23-06.md
Documentação da reunião do dia 23/06.
> Ata da reunião do dia 23/06

- docs/AtasDeReunião/Ata_25-06.md
Documentação da reunião do dia 25/06.
> Ata da reunião do dia 25/06

- docs/AtasDeReunião/Ata_17-06.md
Documentação da reunião do dia 17/06.
#46
> Ata de reunião do dia 17/06

- docs/Base/ParticipacoesBase/participacoes_base.md
- docs/CONTRIBUTING.md
Fiz textos para branch e commit além de colocar hyperlink para os manuais feitos pelos colegas
> add: commit text and branch text

- docs/AtasDeReunião/Ata_29-06.md
Documentação da Ata de reunião do dia 29-06.
> Ata de reunião do dia 29-06

- docs/AtasDeReunião/Ata_02-06.md
Documentação da ata de reunião do dia 02-07.
> Ata de reunião do dia 02-07

- docs/AtasDeReunião/Ata_06-07.md
Documentação da ata de reunião do dia 06-07.
> docs: Adicionando a ata de reunião 06-07

- docs/Base/AbordagemNaoEspecifica/elicitacao/introspeccao.md
Detalhamento do método e a metodologia utilizada.
> Melhoria do documento de introspecção

- docs/Modelagem/NFR_Framework.md
> docs:Inserção do documento extra de NFR Framework

- docs/CONTRIBUTING.md
- docs/_sidebar.md
Adiciona a rota do modelo do diagrama de sequência
Por favor verifiquem o arquivo  [diagrama de sequência](https://github.com/UnBArqDsw2022-1/2022.1_G4_FluxoAgil/blob/main/docs/Modelagem/UMLDinamicos/diagramaDeSequencia.md)
> docs/ adicionando rota de navegação e arrumando contributing

- docs/Modelagem/2.2.IniciativasExtras.md
- docs/Modelagem/2.3.ParticipacoesModelagem.md
- docs/_sidebar.md
Iniciativas extra e Participações.
> docs: criacao dos documentos (#113)

- policies/branch_policy.md
Alteração simples das nomenclaturas utilizadas nas branches.
> Correção das nomenclaturas de branch

- docs/Modelagem/backlog.md
- docs/_sidebar.md
> docs: adiciona backlog

- docs/Modelagem/NFR_Framework.md
Correção dos diagramas de confiabilidade e usabilidade.
> fix: Correção dos diagramas

- docs/Base/AbordagemNaoEspecifica/elicitacao/personas.md
Adicionei o tópico de metodologias no documento de personas, explicando como ele foi elaborado.
> docs: adicionando metodologia

- docs/Base/AbordagemNaoEspecifica/priorizacao/moscow.md
Alguns dos requisitos não foram elicitados corretamento:
- `RF13` Inválido: horas escolhidas de que?
- `RF28` Não funcional
- `RF29` Não funcional
- `RF34` Inválido: o que é a qualidade?
- `RF35` Funcionalidade ou épico
- `RF37` Inválido: múltiplas interpretações
- Documentation update
> Corrige requisitos inválidos

- docs/Sprints/Sprint3/planejamento_sprint3.md
- docs/Sprints/Sprint3/resultados_sprint3.md
> docs: adicao dos documentos (#141)

- docs/Sprints/Sprint5/planejamento_sprint5.md
- docs/Sprints/Sprint5/resultados_sprint5.md
- docs/_sidebar.md
Documentação sprint 5
- [x Any dependent changes have been merged and published in downstream modules.
> 156 docs/sprint 5

- docs/AtasDeReunião/Ata_02-08.md
> docs: Ata de reunião dia 02/08

- docs/AtasDeReunião/Ata_08-08.md
> docs: Ata de reunião dia 08/08

- docs/Sprints/Sprint6/planejamento_sprint6.md
- docs/Sprints/Sprint6/resultados_sprint6.md
- docs/_sidebar.md
> 169 docs/sprint 6

- docs/PadroesDeProjeto/3.3.PadroesExtra.md
- docs/_sidebar.md
De acordo com issue 151, faz necessario criar uma documentação explicando padrões de projetos extras. 
> 151 docs/padrões de projeto emergentes

- docs/AtasDeReunião/Ata_01-08.md
> docs: Ata de reunião dia 01/08

- docs/ArquiteturaReutilizacao/4.2.ReutilizacaoDeSoftware.md
- docs/ArquiteturaReutilizacao/4.3.IniciativasExtras.md
- docs/Sprints/Sprint10/planejamento_sprint10.md
- docs/Sprints/Sprint10/resultados_sprint10.md
- docs/Sprints/Sprint11/planejamento_sprint11.md
- docs/Sprints/Sprint11/resultados_sprint11.md
- docs/Sprints/Sprint7/planejamento_sprint7.md
- docs/Sprints/Sprint7/resultados_sprint7.md
- docs/Sprints/Sprint8/planejamento_sprint8.md
- docs/Sprints/Sprint8/resultados_sprint8.md
- docs/Sprints/Sprint9/planejamento_sprint9.md
- docs/Sprints/Sprint9/resultados_sprint9.md
- docs/_sidebar.md
> 185 docs/docs sprint reutilizacao

- docs/AtasDeReunião/Ata_15-08.md
> Ata de reunião 15/08

- docs/AtasDeReunião/Ata_22-08.md
> Ata de reunião 22/08

- docs/Modelagem/bancoDeDados2.md
- docs/_sidebar.md
> 29 docs/v2 banco de dados
